### ISSUE TITLE
"FSL BET did not run and no previous mask was found.. Reconstruction stopped"

### ISSUE THREAD

**Issue by Wangyulin-user** [xuli99/JHUKKI_QSM_Toolbox#3]
Thank you for your wonderful job. But as the title mentioned, the toolbox can't run FSL BET even though I had FSL installed in usr/local/fsl directory. I wonder is this because the input image format? I used .dcm format of phase images.

**Comment by xuli99** [comment]
This should not be related to the .dcm format. It is more related to the fsl installation and whether you can call fsl from matlab. Previous version may have issue with PC (needs to run under a virtual machine). I have added support for Windows wsl now.
